services:
  lang-server:
    container_name: lang-server
    build:
      context: $DSL_REPO_PATH/
      dockerfile: $DSL_REPO_PATH/Dockerfile
    volumes:
      - $DSL_LOGS_PATH:/opt/logs/:wr
      - $SHARED_WORKSPACE_PATH:/home/user/workspace/:wr
    ports:
      - "5007:5007"
    networks:
      - independent

  ide:
    container_name: ide
    build:
      context: $IDE_REPO_PATH/
      dockerfile: $IDE_REPO_PATH/Dockerfile
    environment:
      - CODE_SERVER_HOST=0
      - CODE_SERVER_PORT=8080
      - CODE_SERVER_ORIGIN=$IDE_HOST_URL
      - CODE_SERVER_WELCOME_TEXT="WELCOME TO XXP IDE"
      - LANG_SERVER_HOST=lang-server
      - LANG_SERVER_PORT=5007
    volumes:
      - $SHARED_WORKSPACE_PATH:/home/user/workspace/:wr
      - $IDE_LOGS_PATH/:/etc/xxp-lang-server/logs/:wr
    ports:
      - "8080:8080"    
    depends_on:
      - lang-server
    networks:
      - independent
  
networks:
  independent:
    driver: bridge
    

